# Generated by Django 3.2.9 on 2021-12-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('gameTitle', models.CharField(max_length=100)),
                ('reviewTitle', models.CharField(max_length=100)),
                ('reviewBody', models.TextField(max_length=10000)),
            ],
        ),
    ]
