# Generated by Django 3.2.9 on 2021-12-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg', '0004_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=1000),
        ),
    ]
